name: Build and Deploy to GitHub Pages

# 1) Trigger on every push to the 'main' branch
on:
  push:
    branches:
      - main

# 2) Grant the GITHUB_TOKEN permission to update Pages
permissions:
  contents: read   # needed to check out source code
  pages: write     # needed to push to gh-pages
  id-token: write  # needed by the deploy-pages action

jobs:
  build:
    name: Build React App
    runs-on: ubuntu-latest

    steps:
      # ──────────────────────────────────────────────────────────────
      # 2.1 Checkout your repository (reads from main)
      - name: Check out source code
        uses: actions/checkout@v4

      # ──────────────────────────────────────────────────────────────
      # 2.2 Set up Node.js 18.x
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # ──────────────────────────────────────────────────────────────
      # 2.3 Install all dependencies (reads package.json / yarn.lock)
      - name: Install dependencies
        run: npm install

      # ───────────
