# File: .github/workflows/main.yml
name: Build and Deploy to GitHub Pages

# 1) Trigger on every push to the 'main' branch
on:
  push:
    branches:
      - main

# 2) Give this workflow the permissions it needs to publish to GitHub Pages
permissions:
  contents: read   # required to check out your code
  pages: write     # needed by actions/deploy-pages to push to gh-pages
  id-token: write  # required by actions/deploy-pages

jobs:
  build:
    name: Build React App
    runs-on: ubuntu-latest

    steps:
      # ──────────────────────────────────────────────────────────────
      # 2.1 Checkout your repository (reads from main)
      - name: Check out source code
        uses: actions/checkout@v4

      # ──────────────────────────────────────────────────────────────
      # 2.2 Set up Node.js 18.x
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # ──────────────────────────────────────────────────────────────
      # 2.3 Install all dependencies, using npm (package.json / package-lock.json)
      - name: Install dependencies
        run: npm install

      # ──────────────────────────────────────────────────────────────
      # 2.4 Run the build script (react-scripts build → puts a production build in build/)
      - name: Build production bundle
        run: npm run build

      # ──────────────────────────────────────────────────────────────
      # 3. Upload the entire contents of build/ as the “pages” artifact
      #    This artifact will later be deployed to gh-pages branch.
      - name: Upload build output for deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build

    steps:
      # ──────────────────────────────────────────────────────────────
      # 4. Download the “build” artifact from the previous job
      - name: Download build artifact
        uses: actions/download-pages-artifact@v2

      # ──────────────────────────────────────────────────────────────
      # 5. Deploy the downloaded contents to GitHub Pages (gh-pages branch)
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        # No extra input is needed: the action will automatically push what it downloaded
        # into the gh-pages branch, at root, then GitHub Pages will serve it.

