name: Build and Deploy to GitHub Pages

# 1) Trigger on every push to the 'main' branch
on:
  push:
    branches:
      - main

# 2) Grant the GITHUB_TOKEN permission to update Pages
permissions:
  contents: read   # to check out source code
  pages: write     # to push to gh-pages
  id-token: write  # needed by the gh-pages action

jobs:
  build-and-publish:
    name: Build React App and Publish to gh-pages
    runs-on: ubuntu-latest

    steps:
      # ─────────────────────────────────────────────────
      # 2.1 Checkout your repository at the commit that triggered this workflow
      - name: Check out source code
        uses: actions/checkout@v4

      # ─────────────────────────────────────────────────
      # 2.2 Setup Node.js (we’ll use v18.x to match CRA’s recommended version)
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # ─────────────────────────────────────────────────
      # 2.3 Install dependencies (reads package.json + package-lock.json)
      - name: Install dependencies
        run: npm install

      # ─────────────────────────────────────────────────
      # 2.4 Build the React app for production
      - name: Build
        run: npm run build

      # ─────────────────────────────────────────────────
      # 2.5 Deploy the `build/` folder to the `gh-pages` branch using the gh-pages package
      - name: Deploy to GitHub Pages
        run: npm run deploy
