name: Build and Deploy to GitHub Pages

# Trigger this workflow whenever someone pushes to main
on:
  push:
    branches:
      - main

# Give the built‐in GITHUB_TOKEN permission to update Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build React app
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Upload build output as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-pages-artifact@v2

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
